language: node_js
node_js:
  - 0.8
env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - BASE_DIR: .
# This extra install section is only necessary if your project has already installed AMD dependencies like Dojo using
# npm, since AMD path resolution does not follow Node.js path resolution rules but npm does not know this
install:
  - npm install
  - cd node_modules/intern
  - npm install --production
  - cd ../..
script: node_modules/.bin/intern-client config=src/app/tests/intern